      <div id="jsn-content" class="jsn-hasright ">
        <div id="jsn-content_inner">
          <div id="jsn-content_inner1">
            <div id="jsn-content_inner2">
              <div id="jsn-content_inner3">
                <div id="jsn-content_inner4">
                  <div id="jsn-content_inner5">
                    <div id="jsn-content_inner6">
                      <div id="jsn-content_inner7">
                        <div id="jsn-maincontent">
                          <div id="jsn-centercol">
                            <div id="jsn-centercol_inner">
                              <div id="jsn-mainbody-content">
                                <div id="jsn-mainbody">
                                  <div id="system-message-container"></div>
                                  <div class="com-content ">
                                    <div class="article">
                                      <h2 class="contentheading">Укрінтеравтосервіс</h2>
                                      <div class="jsn-article-toolbar">
                                        <ul class="jsn-article-tools">
                                          <li class="jsn-article-print-button">
                                            <a href="/?tmpl=component&amp;print=1&amp;page=" class="jsn-article-print-button" title="Печать" onclick="window.open(this.href,'win2','status=no,toolbar=no,scrollbars=yes,titlebar=no,menubar=no,resizable=yes,width=640,height=480,directories=no,location=no'); return false;" rel="nofollow">&nbsp;</a>						</li>
                                            <li class="jsn-article-email-button">
                                              <a href="/index.php/component/mailto/?tmpl=component&amp;template=jsn_epic_free&amp;link=d77c04c704cd51e705ff13bcffef2bd446b79007" class="jsn-article-email-button" title="E-mail" onclick="window.open(this.href,'win2','width=400,height=350,menubar=yes,resizable=yes'); return false;">&nbsp;</a>						</li>



                                            </ul>



                                            <div class="clearbreak"></div>
                                          </div>


                                          <div class="jsn-article-content">
                                            <div class="content-links">
                                            </div>

                                            <p align="center" style="margin: 0cm 0cm 0pt; text-align: center;" abp="2226">&nbsp;</p>
                                            <p align="center" style="margin: 0cm 0cm 0pt; text-align: center;" abp="2258"><span style="font-size: x-large;" abp="2259"><b abp="2260"><span abp="2261"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2262">До уваги перевізників</span></span></b></span></p>
                                            <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.45pt;" abp="2263"><span style="font-size: large;" abp="2264"><span abp="2265"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2266">На доповнення інформації від Укртрансінспекції, опублікованої на сайті (</span><a href="http://www.uti.gov.ua/" abp="2267"></a><a href="http://www.uti.gov.ua/" abp="2268"><span style="color: windowtext; text-decoration: none;" abp="2269"><span style="text-decoration: underline;" abp="2270"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2271"></span></span></span></a><span style="color: #0000ff; text-decoration: underline;" abp="2272"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2273"><a href="http://www.uti.gov.ua" abp="2274"><span style="color: #0000ff; text-decoration: underline;" abp="2275">http://www.uti.gov.ua</span></a></span></span></span><span style="font-family: Times New Roman;" face="Times New Roman" abp="2276">), <span abp="2277">повідомляємо, що перевізники, які уклали договір з УДП «Укрінтеравтосервіс», можуть як і раніше надавати відривні листи бортових журналів ліцензій ЄКМТ до Управління транспортних перевезень УДП «Укрінтеравтосервіс» поштою або нарочно, відповідно до вимог Наказу Міністерства транспорту України від 20.08.2004 № 757, а саме:</span></span></span></p>
                                            <ul style="list-style-type: disc; direction: ltr;" abp="2278">
                                              <li style="color: #000000; font-style: normal; font-weight: normal;" abp="2279">
                                                <p style="text-align: justify; color: #000000; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 0pt;" abp="2280"><span style="line-height: 115%; font-family: 'Times New Roman','serif'; font-size: large;" abp="2281">До 15 числа місяця наступного за звітним, разом з супровідним листом.</span></p>
                                                <p style="text-align: justify; color: #000000; font-family: 'Calibri','sans-serif'; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 10pt;" abp="2282"><span style="line-height: 115%; font-family: 'Times New Roman','serif'; font-size: large;" abp="2283">Узагальнена інформація, щодо ефективності використання дозволів ЄКМТ, зведена Управлінням транспортних перевезень УДП «Укрінтеравтосервіс», буде надана до <span abp="2284">Комісії з питань аналізу ефективності використання дозволів ЄКМТ.</span></span></p>
                                              </li>
                                            </ul>
                                            <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.45pt;" abp="2285"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2286"><span abp="2287">Контакти Управління</span><span abp="2288">:</span></span></p>
                                            <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.45pt;" abp="2289"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2290"><span abp="2291">Тел.</span><span abp="2292">:</span><span abp="2293"> (044) 590 – 10 – 77 (78), (044) 524 – 95 – 32</span></span><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2290"><span abp="2293"><br /></span></span></p>
                                            <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.45pt;" abp="2289"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2290"><span abp="2293"></span></span><hr /><hr />
                                              <p>&nbsp;</p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2294"><span style="font-family: Times New Roman; font-size: small;" face="Times New Roman" abp="2295" size="3"> </span>&nbsp;</p>
                                              <p align="right" style="background: white; margin: 7.5pt 0cm 0pt 180pt; text-align: right; line-height: 13.5pt;" abp="2296"><b abp="2297"><span style="color: black; font-size: 13.5pt;" abp="2298"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2299">УВАГА!!!!</span></span></b></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2300"><br abp="2301" /></p>
                                              <p align="right" style="background: white; margin: 7.5pt 0cm 0pt 112.5pt; text-align: right; line-height: 13.5pt;" abp="2302"><b abp="2303"><span style="color: black; font-size: 13.5pt;" abp="2304"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2305">Оформлення документів ЄКМТ</span></span></b></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2306"><br abp="2307" /></p>
                                              <p align="right" style="background: white; margin: 7.5pt 0cm 0pt 112.5pt; text-align: right; line-height: 13.5pt;" abp="2308"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2309"><b abp="2310"><span style="text-decoration: underline;" abp="2311"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2312">Починаючи з &nbsp;0</span></span></b><b abp="2313"><span style="text-decoration: underline;" abp="2314"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2315">3</span></span></b><b abp="2316"><span style="text-decoration: underline;" abp="2317"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2318">.0</span></span></b><b abp="2319"><span style="text-decoration: underline;" abp="2320"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2321">3</span></span></b><b abp="2322"><span style="text-decoration: underline;" abp="2323"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2324">.201</span></span></b><b abp="2325"><span style="text-decoration: underline;" abp="2326"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2327">5</span></span></b></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2328"><br abp="2329" /></p>
                                              <p align="right" style="background: white; margin: 7.5pt 0cm 7.5pt 112.5pt; text-align: right; line-height: 13.5pt;" abp="2330"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2331"><b abp="2332"><span style="text-decoration: underline;" abp="2333"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2334"> </span></span></b><b abp="2335"><span style="text-decoration: underline;" abp="2336"><span style="color: black; font-size: 13.5pt; text-decoration: underline;" abp="2337">Оформлення бортових журналів</span></span></b><b abp="2338"><span style="color: black; font-size: 13.5pt;" abp="2339">&nbsp;здійснюватиметься в&nbsp;&nbsp;&nbsp;&nbsp;</span></b></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2340"><br abp="2341" /></p>
                                              <p align="right" style="background: white; margin: 7.5pt 0cm 7.5pt 112.5pt; text-align: right; line-height: 13.5pt;" abp="2342"><b abp="2343"><span style="color: black; font-size: 13.5pt;" abp="2344"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2345">УДП «Укрінтеравтосервіс» - (м. Київ Просп. Науки 57)</span></span></b></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2346"><br abp="2347" /></p>
                                              <p align="center" style="background: white; margin: 7.5pt 0cm; text-align: center; line-height: 13.5pt;" abp="2348"><strong abp="2349"><span style="color: black; font-size: 13.5pt;" abp="2350"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2351">&nbsp;</span></span></strong></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2352"><br abp="2353" /></p>
                                              <p align="center" style="background: white; margin: 7.5pt 0cm; text-align: center; line-height: 13.5pt;" abp="2354"><span style="font-size: x-large;" abp="2355"><span style="color: black;" abp="2356"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2357"><strong abp="2358">До уваги автомобільних перевізників!!!</strong></span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2359"><br abp="2360" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2361"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2362"><span style="color: black; font-size: 13.5pt;" abp="2363">&nbsp; </span><span style="font-size: 14pt;" abp="2364">У зв’язку з перерозподілом залишку дозволів оформлення та видачі автомобільним&nbsp;перевізникам документів Європейської Конференції Міністрів Транспорту&nbsp;(ЄКМТ) за результатами їх конкурсного розподілу на 2015 рік, доводимо до&nbsp;відома короткий порядок оформлення та подачі документів для отримання&nbsp;дозволів та бортових журналів ЄКМТ.</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2365"><br abp="2366" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2367"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2368"><span style="font-size: 14pt;" abp="2369">1.Оформлення та видача</span><span style="font-size: 14pt;" abp="2370">, </span><span style="font-size: 14pt;" abp="2371">Бортового журналу ЄКМТ&nbsp;здійснюватиметься за адресою м. Київ проспект Науки 57 (територія&nbsp;УДП «Укрінтеравтосервіс»).</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2372"><br abp="2373" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2374"><span style="font-size: 14pt;" abp="2375"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2376">2.Для оформлення комплекту документів (дозволу ЄКМТ та Бортового&nbsp;журналу до дозволу ЄКМТ) заявки подаються окремо до:</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2377"><br abp="2378" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2379"><span style="font-size: 14pt;" abp="2380"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2381">а) Державної інспекції України з безпеки на наземному транспорті для оформлення дозволу ЄКМТ (детальна інформація щодо&nbsp;порядку оформлення та необхідних документів розміщена на сайті&nbsp;Укртрансінспекції України за адресою&nbsp;</span><a href="http://www.uti.gov.ua/" abp="2382"></a><a href="http://www.uti.gov.ua/" abp="2383"><span style="color: windowtext; text-decoration: none;" abp="2384"><span style="text-decoration: underline;" abp="2385"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2386"></span></span></span></a><span style="color: #0000ff;" abp="2387"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2388"><a href="http://www.uti.gov.ua" abp="2389"><span style="color: #0000ff;" abp="2390">http://www.uti.gov.ua</span></a></span></span></span><span style="font-family: Times New Roman;" face="Times New Roman" abp="2391">&nbsp;);</span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2392"><br abp="2393" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2394"><span style="font-size: 14pt;" abp="2395"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2396">б)УДП «Укрінтеравтосервіс» для оформлення Бортового журналу&nbsp;ЄКМТ та супутнього комплекту документів.</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2397"><br abp="2398" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2399"><span style="font-size: 14pt;" abp="2400"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2401">3.Вартість Бортового журналу ЄКМТ та оформлення супутніх&nbsp;документів (договору, бланка зобов’язання, інформаційного листа)&nbsp;разом становить 1180,00 гривень за одиницю, в тому числі ПДВ 20%.</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2402"><br abp="2403" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2404"><span style="font-size: 14pt;" abp="2405"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2406">4.Для отримання рахунку по оплаті послуг з оформлення та&nbsp;обслуговуванню Бортових журналів ЄКМТ, перевізник оформлює&nbsp;заявку, згідно форми наведеної нижче, та подає її в комплекті з:</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2407"><br abp="2408" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2409"><span style="font-size: 14pt;" abp="2410"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2411">- копією свідоцтва платника податків,</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2412"><br abp="2413" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2414"><span style="font-size: 14pt;" abp="2415"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2416">- копією свідоцтва про реєстрацію, (обо витяга/виписки з ЄДР)</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2417"><br abp="2418" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2419"><span style="font-size: 14pt;" abp="2420"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2421">наручно або за телефонами факсами наведеними нижче.</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2422"><br abp="2423" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2424"><span style="font-size: 14pt;" abp="2425"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2426">5.Для отримання Бортових журналів представник підприємства прибуває&nbsp;до УДП «Укрінтеравтосервіс» з оформленим договором зі сторони&nbsp;підприємства, згідно форми наведеної нижче, а у разі оформлення&nbsp;даного договору безпосередньо в УДП «Укрінтеравтосервіс»,&nbsp;представник підприємства повинен бути наділений правом підпису&nbsp;(відповідним дорученням, наказом, розпорядженням тощо).</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2427"><br abp="2428" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2429"><span style="font-size: 14pt;" abp="2430"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2431">6.Для отримання Бортових журналів ЄКМТ представник підприємства&nbsp;має прибути з дорученням від підприємства (форма №М-2).</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2432"><br abp="2433" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2434"><span style="font-size: 14pt;" abp="2435"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2436">7.Оплата за рахунком по оплаті послуг з оформлення та обслуговуванню&nbsp;Бортових журналів ЄКМТ, може бути здійснена в готівковій формі&nbsp;безпосередньо в касі УДП «Укрінтеравтосервіс».</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2437"><br abp="2438" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2439"><span style="font-size: 14pt;" abp="2440"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2441">8.УВАГА процедуру оформлення документів ЄКМТ слід здійснювати&nbsp;починаючи з подачі заявки/листа на отримання дозволу ЄКМТ у&nbsp;відповідності до форми та порядку визначеної Укртрансінспекцією&nbsp;України (</span><a href="http://www.uti.gov.ua/" abp="2442"></a><a href="http://www.uti.gov.ua/" abp="2443"><span style="color: windowtext; text-decoration: none;" abp="2444"><span style="text-decoration: underline;" abp="2445"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2446"></span></span></span></a><span style="color: #0000ff;" abp="2447"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2448"><a href="http://www.uti.gov.ua" abp="2449"><span style="color: #0000ff;" abp="2450">http://www.uti.gov.ua</span></a></span></span></span><span style="font-family: Times New Roman;" face="Times New Roman" abp="2451">).</span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2452"><br abp="2453" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2454"><span style="color: #ff0000; font-size: 14pt;" abp="2455"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2456"><strong abp="2457"><span style="font-size: x-large;" abp="2458">Важливо</span></strong>:</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2459"><br abp="2460" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2461"><span style="color: #ff0000; font-size: 14pt;" abp="2462"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2463">1.При заміні бортового журналу, в разі заміни дозволу ЄКМТ, вартість послуги складає 100грн., в тому числі ПДВ 20%.</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2464"><br abp="2465" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2466"><span style="color: #ff0000; font-size: 14pt;" abp="2467"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2468">2.В УДП «Укрінтеравтосервіс» змінено реквізити на оплату комплекту документів ЄКМТ, та раніше виставлені рахунки також просимо сплачувати на:</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2469"><br abp="2470" /></p>
                                              <p style="margin: 0cm 0cm 0pt; text-align: justify; text-indent: 35.4pt;" abp="2471"><span style="font-size: 14pt;" abp="2472"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2473">&nbsp;</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2474"><br abp="2475" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2476"><span style="color: #000000;" abp="2477"><span abp="2478"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2479" size="5"><strong abp="2480">УДП «УКРІНТЕРАВТОСЕРВІС»</strong></span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2481"><br abp="2482" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2483"><span style="color: #000000;" abp="2484"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2485" size="5">07362, Київська обл., Вишгородський р-н, </span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2486"><br abp="2487" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2488"><span style="color: #000000;" abp="2489"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2490" size="5">с. Новосілки, вул. Київська, 50</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2491"><br abp="2492" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2493"><span style="color: #000000;" abp="2494"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2495" size="5">Поштова Адреса:</span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2496"><br abp="2497" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2498"><span style="color: #000000; font-family: Times New Roman;" face="Times New Roman" abp="2499"><st1:metricconverter abp="2500" productid="03083, м"><span abp="2501"><span style="font-size: large;" abp="2502" size="5">03083, м</span></span></st1:metricconverter><span abp="2503"><span style="font-size: large;" abp="2504" size="5">. Київ, пр-т Науки, 57 </span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2505"><br abp="2506" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2507"><span style="color: #000000; font-family: Times New Roman;" face="Times New Roman" abp="2508"><span abp="2509"><span style="font-size: large;" abp="2510" size="5">р/р </span></span><span abp="2511"><span style="font-size: large;" abp="2512" size="5">26002010044017</span></span><span abp="2513"><span style="font-size: large;" abp="2514" size="5"> в ВАТ «Укрексімбанк»&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #0000ff; font-size: medium;" abp="2515"><a href="/images/thumbnails/Golovna/Blank_zabovyazan.doc" target="_self" abp="2516"><span style="color: #0000ff; font-family: Arial;" face="Arial" abp="2517" size="2">Скачати Бланк Зобовязання</span></a></span></span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; line-height: normal; text-indent: 42.55pt;" abp="2519"><br abp="2520" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2521"><span style="color: #000000;" abp="2522"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2523"><span abp="2524"><span style="font-size: large;" abp="2525" size="5">&nbsp;</span></span><span style="font-size: large;" abp="2526" size="5">м. Києва МФО 322313,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #0000ff; font-size: medium;" abp="2527"><a href="/images/thumbnails/Golovna/Dodatkova_ugoda_2015_Roku.doc" target="_self" abp="2528"><span style="color: #0000ff; font-family: Arial;" face="Arial" abp="2529" size="2">Скачати Додаткову угоду 2015 року</span></a></span><span style="color: #000000; font-family: Arial; font-size: small;" face="Arial" abp="2530" size="2" color="#000000">&nbsp;</span></span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; line-height: normal; text-indent: 42.55pt;" abp="2531"><br abp="2532" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2533"><span style="color: #000000;" abp="2534"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2535" size="5">код ЄДРПОУ 21536845&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #0000ff; font-size: medium;" abp="2536"><a href="/images/thumbnails/Golovna/Zayava_na_produkziu.doc" target="_self" abp="2537"><span style="color: #0000ff; font-family: Arial;" face="Arial" abp="2538" size="2">Скачати Заяву на продукцію</span></a></span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; line-height: normal; text-indent: 42.55pt;" abp="2540"><br abp="2541" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2542"><span style="color: #000000;" abp="2543"><span style="font-family: Times New Roman; font-size: large;" face="Times New Roman" abp="2544" size="5">ІПН 215368410086, св-во 13696827&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #0000ff; font-size: medium;" abp="2545"><a href="/images/thumbnails/Golovna/Zayava_zamina.doc" target="_self" abp="2546"><span style="color: #0000ff; font-family: Arial;" face="Arial" abp="2547" size="2">Скачати Заяву заміну</span></a></span></span></span></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; line-height: normal; text-indent: 42.55pt;" abp="2549"><br abp="2550" /></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2551"><span style="font-family: Times New Roman;" face="Times New Roman" abp="2552"><span abp="2553"><span style="font-size: large;" abp="2554" size="5">тел./факс 524-</span></span><span abp="2555"><span style="font-size: large;" abp="2556" size="5">95-29, 524-95-32&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size: medium;" abp="2557"><span abp="2558"><a href="/images/thumbnails/Golovna/Zayava.doc" target="_self" abp="2559"><span style="color: #0000ff;" abp="2560"><span style="font-family: Arial;" face="Arial" abp="2561" size="2">Скачати Заяву</span></span></a></span><span style="color: #000000; font-family: Arial;" face="Arial" abp="2562" size="2" color="#000000">&nbsp;</span></span></span></span></span></p>
                                              <p style="margin: 0cm 0cm 0pt;" abp="2563"><br abp="2564" /></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2565"><br abp="2566" /></p>
                                              <p align="center" style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 42.55pt;" abp="2567"><span style="font-family: 'Times New Roman','serif'; font-size: 20pt;" abp="2568"></span>
                                                <p><hr /><hr />
                                                  <p>&nbsp;</p>
                                                  <p abp="2570">&nbsp;</p>
                                                  <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2571"><span style="font-family: 'Times New Roman','serif'; font-size: 20pt;" abp="2572">Стосовно неухильного дотримання норм безпеки при здійсненні міжнародних регулярних перевезень пасажирів автомобільним транспортом!</span></p>
                                                  <p align="center" style="margin: 0cm 0cm 0pt; text-align: center; line-height: normal; text-indent: 42.55pt;" abp="2573"><span style="font-family: 'Times New Roman','serif'; font-size: 20pt;" abp="2574">&nbsp;</span></p>
                                                  <p style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 35.4pt;" abp="2575"><span style="font-family: 'Times New Roman','serif'; font-size: 16pt;" abp="2576">Шановні автоперевізники, відповідно до листа Міністерства інфраструктури України від 18.02.2015 № 633/25/14-15 (копія додається) УДП «Укрінтеравтосервіс» звертаєВашу увагу на необхідність неухильного дотримання норм безпеки при здійсненні міжнародних регулярних перевезень пасажирів автомобільним транспортом та про можливість внесення змін до функціонуючих регулярних автомобільних маршрутів, що проходять територіями Донецької та Луганської областей, Автономної республіки Крим.</span></p>
                                                  <p style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 35.4pt;" abp="2577"><span style="font-family: 'Times New Roman','serif'; font-size: 16pt;" abp="2578">При цьому, нагадуємо, що внесення змін до функціонуючих регулярних автомобільних маршрутів повинно відбуватись відповідно до положень Порядку організації регулярних, нерегулярних і маятникових перевезень пасажирів автомобільним транспортом у міжнародному сполученні затвердженого наказом Міністерства транспорту України від 09.02.2004 № 75, який зареєстровано в Міністерстві юстиції України 22 червня 2004 року за № 759/9358.</span></p>
                                                  <p style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 35.4pt;" abp="2579"><span style="font-family: 'Times New Roman','serif'; font-size: 16pt;" abp="2580">&nbsp;</span></p>
                                                  <p style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 35.4pt;" abp="2581"><span style="font-family: 'Times New Roman','serif'; font-size: 16pt;" abp="2582">У разі виникнення питань щодо вищевказаної інформації, підготовки документів для внесення змін до функціонуючих регулярних автомобільних маршрутів УДП «Укрінтеравтосервіс» просить звертатись автомобільних перевізників до Управління транспортних перевезень (тел. (044) 524-95-32, (044) 524-95-29).</span></p>
                                                  <p style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 35.4pt;" abp="2583"><span style="font-family: 'Times New Roman','serif'; font-size: 16pt;" abp="2584">&nbsp;</span></p>
                                                  <p style="margin: 0cm 0cm 0pt; text-align: justify; line-height: normal; text-indent: 35.4pt;" abp="2585"><span style="font-family: 'Times New Roman','serif'; font-size: 16pt;" abp="2586">&nbsp;</span></p>
                                                  <p abp="2587"><br abp="2588" /></p>
                                                  <hr abp="2589" /><hr abp="2590" />
                                                  <p abp="2591">&nbsp;</p>
                                                  <p style="text-indent: 49.65pt;" abp="2592"><span style="font-size: 16pt; line-height: 115%; font-family: 'Times New Roman', serif;" abp="2593">Громадяни України з АР Крим та м. Севастополя для вирішення питань, пов’язаних з тимчасовим перебуванням в інших регіонах України, можуть звернутися за телефоном</span></p>
                                                  <p abp="2594">&nbsp;</p>
                                                  <p align="center" style="text-align: center;" abp="2595"><b abp="2596"><span style="font-size: 18pt; font-family: 'Times New Roman', serif;" abp="2597">урядової «гарячої лінії»</span></b></p>
                                                  <p align="center" style="text-align: center;" abp="2598"><b abp="2599"><span style="font-size: 18pt; font-family: 'Times New Roman', serif;" abp="2600">0&nbsp;800&nbsp;507&nbsp;309</span></b></p>
                                                  <p align="center" style="text-align: center;" abp="2601"><span style="font-size: 14pt; font-family: 'Times New Roman', serif;" abp="2602">(дзвінки зі стаціонарних &nbsp;телефонів у межах україни безкоштовні)</span><span style="font-family: 'Times New Roman', serif; font-size: 14pt; line-height: 1.5;" abp="2603">&nbsp;</span></p>
                                                  <p abp="2604">&nbsp;</p>
                                                  <p align="center" style="text-align: center;" abp="2605"><span style="font-size: 14pt; font-family: 'Times New Roman', serif;" abp="2606">Звернутися також можна на веб-сайт</span></p>
                                                  <p align="center" style="text-align: center;" abp="2607"><span style="color: #000080;" abp="2608"><a style="font-family: 'Times New Roman', serif; font-size: 16pt; line-height: 115%;" href="http://www.ukc.gov.ua" abp="2609"><span style="color: #000080;" abp="2610">www.ukc.gov.ua</span></a><span style="font-family: 'Times New Roman', serif; font-size: 16pt; line-height: 115%;" abp="2611">&nbsp;</span></span></p>
                                                  <p abp="2612">&nbsp;</p>
                                                  <p align="center" style="text-align: center;" abp="2613"><span style="font-size: 18pt; line-height: 115%; font-family: 'Times New Roman', serif;" abp="2614">Урядова телефонна «гаряча лінія» працює цілодобово</span></p>
                                                  <p align="center" style="text-align: center;" abp="2615"><span style="font-size: 18pt; line-height: 115%; font-family: 'Times New Roman', serif;" abp="2616">&nbsp;</span><span style="font-size: 18pt; line-height: 115%; font-family: 'Times New Roman', serif;" abp="2617"><br abp="2618" /></span></p>
                                                  <p align="center" style="text-align: center;" abp="2619"><span style="font-family: verdana, geneva; font-size: medium;" abp="2620"><b abp="2621">«Гаряча лінія» для вирішення «гарячих» питань. </b></span></p>
                                                  <p align="center" style="text-align: center;" abp="2622"><b style="font-family: verdana, geneva; font-size: small; line-height: 1.5;" abp="2623">&nbsp;</b></p>
                                                  <p style="text-indent: 35.4pt;" abp="2624"><span style="font-family: verdana, geneva; font-size: small;" abp="2625"><b abp="2626">Українським державним підприємством «Укрінтеравтосервіс», що стало базовим для реформування державних підприємств сфери автомобільного транспорту відповідно до наказу Міністерства інфраструктури України від 21.06.2013 № 423, проведено суттєву роботу щодо початку роботи приєднаних підприємств у вигляді нових філій. </b></span></p>
                                                  <p abp="2627"><span style="font-family: verdana, geneva; font-size: small;" abp="2628"><b abp="2629">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Нагадаємо, що до УДП «Укрінтеравтосервіс» було приєднано 25 автомобільних учбових комбінатів та ще понад 10 інших підприємств галузі.</b></span></p>
                                                  <p abp="2630"><span style="font-family: verdana, geneva; font-size: small;" abp="2631"><b abp="2632">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Таким чином, закінчуючи, так би мовити, підготовчий етап у становленні нових можливостей підприємства, УДП «Укрінтеравтосервіс» налаштовується на серйозну роботу щодо створення загальнодержавної мережі із сервісного обслуговування та надання термінової технічної та консультаційної підтримки вітчизняним та іноземним перевізникам, водіям, та пасажирам транспортних засобів.</b></span></p>
                                                  <p style="text-indent: 35.4pt;" abp="2633"><span style="font-family: verdana, geneva; font-size: small;" abp="2634">Так, на виконання доручення Мінінфраструктури, &nbsp;7 лютого в Українському державному підприємстві &nbsp;«Укрінтеравтосервіс» організовано роботу «гарячої лінії» з питань міжнародних автомобільних перевезень. </span></p>
                                                  <p style="text-indent: 35.4pt;" abp="2635"><span style="font-family: verdana, geneva; font-size: small;" abp="2636">Будь-які скарги, зауваження та пропозиції стосовно оформлення, видачі та повернення дозволів на здійснення міжнародних автоперевезень приймаються за телефонними номерами: 044-590-11-11 (тел./факс), 050-334-79-79 (моб.), а для операторів МТС – 505. Також, свої звернення громадяни можуть надсилати на електронну адресу: <a href="mailto:sos@uaservice.com.ua" abp="2637"><span style="color: windowtext;" abp="2638"></span></a><span style="color: #000080;" abp="2639"><a href="mailto:sos@uaservice.com.ua" abp="2640"><span style="color: #000080;" abp="2641">sos@uaservice.com.ua</span></a>.</span> Працюватиме «гаряча лінія» щодня, окрім вихідних та святкових днів, з 7:00 до 19:00.</span></p>
                                                  <p abp="2642"><span style="font-family: verdana, geneva; font-size: small;" abp="2643">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;«Гаряча лінія» є першим кроком на шляху створення потужної служби підтримки «SOS», діяльність якої підприємство планує організувати у найближчому майбутньому.</span></p>
                                                  <p style="text-indent: 35.4pt;" abp="2644"><span style="font-family: verdana, geneva; font-size: small;" abp="2645">УДП «Укрінтеравтосервіс», що на сьогодні представлене у більш як 80 населених пунктах по всій території України, як філіями, так і окремими пунктами автомобільного сервісу, має технічні та організаційні можливості для того, щоб створити систему консультативної, технічної, правової, сервісної підтримки водіїв транспортних засобів, користувачів транспортних послуг, перевізників.</span></p>
                                                  <p style="text-indent: 35.4pt;" abp="2646"><span style="font-family: verdana, geneva; font-size: small;" abp="2647">Підприємство, як своїми, так і залученими технічними ресурсами та спеціалістами, планує надавати термінову допомогу учасникам дорожнього руху та користувачам транспортних послуг щодо евакуації транспортних засобів, технічної допомоги, оперативного ремонту, надання консультацій з питань правового захисту та супроводу (пов’язаних, наприклад, із дорожньо-транспортними пригодами), надання довідкової інформації із різноманітних питань, пов’язаних з перевезеннями (наприклад, при виїзді за кордон) тощо.</span></p>
                                                  <p style="text-indent: 35.4pt;" abp="2648"><span style="font-family: verdana, geneva; font-size: small;" abp="2649">Потрібно зауважити, що створити таку службу планується за європейським досвідом, коли при виникненні у перевізника, в тому числі і з іншої країни, певних проблем із технічним станом автомобіля, або із контролюючими організаціями, служба підтримки може додатково працювати як координатор між водієм та перекладачем, юристом, представником страховика, митним брокером та іншими спеціалістами чи організаціями (або й навіть забезпечити доставку їх до місця пригоди).&nbsp; </span></p>
                                                  <p abp="2650"><span style="font-family: verdana, geneva; font-size: small;" abp="2651">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Такі послуги надаватимуться цілодобово за зручними телефонними номерами, одним з яких вже зараз є короткий номер для операторів МТС – 505, який символічно уособлює міжнародний сигнал «SOS», та за яким служба підтримки підприємства завжди прийде на допомогу!</span></p>
                                                  <p abp="2652"><span style="font-family: verdana, geneva; font-size: small;" abp="2653">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Для планування мережі служби підприємство запрошує до співробітництва суб’єктів господарювання, які спеціалізуються на наданні технічної допомоги, евакуації транспортних засобів, а також спеціалістів в галузі внутрішніх та міжнародних перевезень, в галузі права, для організації в подальшому співпраці на взаємно вигідних умовах. Із зазначених питань пропонуємо звертатися до УДП «Укрінтеравтосервіс».&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
                                                  <p abp="2654"><span style="font-size: small; font-family: verdana, geneva;" abp="2655">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Про подальший хід створення служби буде повідомлятися додатково.</span></p>
                                                  <p align="center" style="text-align: left; margin-left: 150px;" abp="2656"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2657">&nbsp;</span></p>
                                                  <p align="center" style="text-align: left; margin-left: 150px;" abp="2658"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2659">&nbsp;</span></p>
                                                  <p align="center" style="text-align: left; margin-left: 150px;" abp="2660"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2661">&nbsp;</span></p>
                                                  <p align="center" style="text-align: left; margin-left: 150px;" abp="2662"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2663">&nbsp;</span><span style="font-family: 'times new roman', times; font-size: medium; line-height: 115%;" abp="2664">&nbsp;</span></p>
                                                  <p align="center" style="margin-top: 10px; margin-left: 120px; text-align: justify;" abp="2665"><span style="font-family: verdana, geneva; font-size: medium;" abp="2666"><strong abp="2667">Увага !</strong></span></p>
                                                  <p align="center" style="margin-left: 90px; text-align: justify;" abp="2668"><span style="font-family: verdana, geneva; font-size: medium;" abp="2669">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2670">Змінились реквізити для оплати за бортові журнали</span></p>
                                                  <p align="center" style="margin-left: 90px; text-align: justify;" abp="2671"><span style="font-family: verdana, geneva; font-size: medium;" abp="2672">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2673">УДП "Укрінтеравтосервіс"</span></p>
                                                  <p align="center" style="margin-left: 90px; text-align: justify;" abp="2674"><span style="font-family: verdana, geneva; font-size: medium;" abp="2675">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2676">р/р 26006327054701</span></p>
                                                  <p align="center" style="margin-left: 90px; text-align: justify;" abp="2677"><span style="font-family: verdana, geneva; font-size: medium;" abp="2678">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2679">банк ф-л "КРУБанку "Фінанси та кредит" ТОВ</span></p>
                                                  <p align="center" style="margin-left: 90px; text-align: justify;" abp="2680"><span style="font-family: verdana, geneva; font-size: medium;" abp="2681">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2682">м.Київ</span></p>
                                                  <p align="center" style="margin-left: 90px; text-align: justify;" abp="2683"><span style="font-family: verdana, geneva; font-size: medium;" abp="2684">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2685">МФО: 300937</span></p>
                                                  <p align="center" style="margin-bottom: 10px; margin-left: 90px; text-align: justify;" abp="2686"><span style="font-family: verdana, geneva; font-size: medium;" abp="2687">&nbsp;</span><span style="font-family: verdana, geneva; font-size: medium; line-height: 1.5;" abp="2688">ЄДРПОУ: 21536845</span></p>
                                                  <p style="text-indent: 42.55pt; text-align: left; margin-left: 60px;" abp="2689"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2690">&nbsp;</span></p>
                                                  <p style="text-indent: 42.55pt; text-align: left; margin-left: 60px;" abp="2691"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2692">Телефони для довідок</span><span style="text-indent: 42.55pt; line-height: 1.5;" abp="2693">&nbsp;:</span></p>
                                                  <p style="text-indent: 42.55pt; text-align: left; margin-left: 60px;" abp="2694"><span style="line-height: 115%; font-family: 'times new roman', times; font-size: medium;" abp="2695">Управління перевезень – 044-524-28-96</span></p>
                                                  <p style="margin-top: 10px; text-align: center;" abp="2696">&nbsp;</p>
                                                  <p style="margin-top: 10px; text-align: center;" abp="2697">&nbsp;</p>
                                                  <p style="margin-top: 10px; text-align: center;" abp="2698">&nbsp;<strong abp="2699"><span style="font-family: 'times new roman', times; font-size: 12pt; line-height: 18.399999618530273px;" abp="2700">Вельмишановні добродії,&nbsp;колеги !</span></strong></p>
                                                  <p abp="2701"><span style="font-size: 12pt; line-height: 18.399999618530273px; font-family: 'times new roman', times;" abp="2702">&nbsp;</span></p>
                                                  <p style="text-indent: 1cm; text-align: justify;" abp="2703"><span style="font-size: 12pt; line-height: 18.399999618530273px; font-family: 'times new roman', times;" abp="2704">Українське державне підприємство по обслуговуванню іноземних та вітчизняних автотранспортних засобів «Укрінтеравтосервіс» вітає Вас і бажає злагоди та успіху.</span></p>
                                                  <p style="text-indent: 1cm; text-align: justify;" abp="2705"><span style="font-size: 12pt; line-height: 18.399999618530273px; font-family: 'times new roman', times;" abp="2706">Наше підприємство створено згідно наказу Міністерство транспорту та зв’язку України 20 жовтня 1993 року за №376.</span></p>
                                                  <p style="text-indent: 1cm; text-align: justify;" abp="2707"><span style="font-size: 12pt; line-height: 18.399999618530273px; font-family: 'times new roman', times;" abp="2708">Головним завданням поставленим перед новоствореною структурою було і є передусім, надання вітчизняним та іноземним перевізникам усіх видів послуг по обслуговуванню транспортних засобів та членів їх екіпажів на території України та за її межами.</span></p>
                                                  <p style="margin-bottom: 10px; text-indent: 1cm; text-align: justify;" abp="2709"><span style="font-size: 12pt; line-height: 18.399999618530273px; font-family: 'times new roman', times;" abp="2710">На сьогодні УДП «Укрінтеравтосервіс» має розгалужену мережу пунктів автомобільного сервісу на всій території України. Створено і продуктивно працює мережа регіональних підрозділів, які включають в себе філій та 24 пункти автомобільного сервісу.</span></p>
                                                  <p abp="2711"><b style="font-size: medium; line-height: 26.666667938232422px; text-align: center;" abp="2712"><span style="font-family: 'Monotype Corsiva';" abp="2713">&nbsp;<a style="" class="thumbnail" href="/images/EKMT/MAP%2028-01-2014.png" rel="lightbox[111]" title="MAP 28-01-2014" target="_blank"><img width="600" height="425" style="display: block; margin-left: auto; margin-right: auto;" alt="MAP 28-01-2014" src="/images/thumbnails/images/EKMT/MAP 28-01-2014-600x425.png" abp="2714" /></a></span></b></p>
                                                  <p abp="2715">&nbsp;</p>
                                                  <p style="text-align: center;" abp="2716"><span style="color: #000080;" abp="2717"><a href="/images/EKMT/MAP%2028-01-2014%20y.png" abp="2718"><span style="color: #000080;" abp="2719">ЗАВАНТАЖИТИ</span></a></span></p>
                                                  <p abp="2721">&nbsp;</p>
                                                  <p abp="2722">&nbsp;</p>
                                                  <p abp="2723">&nbsp;</p>
                                                  <p abp="2724">&nbsp;</p>
                                                  <p abp="2725">&nbsp;</p>
                                                  <p abp="2726">&nbsp;</p>
                                                  <p abp="2727">&nbsp;</p>
                                                  <p abp="2728">&nbsp;</p>
                                                  <p abp="2729">&nbsp;</p>
                                                  <p abp="2730">&nbsp;</p>
                                                  <p abp="2731">&nbsp;</p>
                                                  <p abp="2732">&nbsp;</p>
                                                  <p abp="2733">&nbsp;</p>
                                                  <p abp="2734">&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                  <p>&nbsp;</p>
                                                </p>
                                              </p>
                                            </p>
                                          </div>
                                          <div class="clearbreak"></div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="clearbreak"></div></div>
